version: '2.4'

services:
  gateway:
    image: rf.gateway.api:1.0
    mem_limit: 500M
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
    hostname: gateway
    environment:
        - ASPNETCORE_ENVIRONMENT=Production
        - ASPNETCORE_URLS=https://+;http://+
        - ASPNETCORE_Kestrel__Certificates__Default__Password=Password.123
        - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/RF-CERT.pfx
    volumes:
      - ${HOME}/.aspnet/https:/https/
    build:
      context: .
      dockerfile: RF.Gateway.Api/Dockerfile
    ports:
      - "17070:443"
    restart: always
    depends_on:
      - consul  
  identity-api:
    image: rf.identity.api:1.0
    mem_limit: 250M
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
    hostname: identity-api
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_URLS=https://+;http://+
        - ASPNETCORE_Kestrel__Certificates__Default__Password=Password.123
        - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/RF-CERT.pfx
    volumes:
      - ${HOME}/.aspnet/https:/https/
    build:
      context: .
      dockerfile: RF.Identity.Api/Dockerfile
    ports:
      - "443"
    restart: always
    depends_on:
      - consul
  userregistration-app:
    image: rf.userregistration.app:1.0
    mem_limit: 200M
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
    hostname: userregistration-app
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ${HOME}/.aspnet/https:/https/
    build:
      context: .
      dockerfile: RF.UserRegistration.App/Dockerfile
    restart: always
    depends_on:
      rabbit:
        condition: service_healthy
  contracts-api:
    image: rf.contracts.api:1.0
    mem_limit: 250M
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
    hostname: contracts-api
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_URLS=https://+;http://+
        - ASPNETCORE_Kestrel__Certificates__Default__Password=Password.123
        - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/RF-CERT.pfx
    volumes:
      - ${HOME}/.aspnet/https:/https/
    build:
      context: .
      dockerfile: RF.Contracts.Api/Dockerfile
    ports:
      - "443"
    restart: always
    depends_on:
      - consul
  contractdeployment-app:
    image: rf.contractdeployment.app:1.0
    mem_limit: 200M
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
    hostname: contractdeployment-app
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ${HOME}/.aspnet/https:/https/
    build:
      context: .
      dockerfile: RF.ContractDeployment.App/Dockerfile
    restart: always
    depends_on:
      rabbit:
        condition: service_healthy
  contentapproval-app:
    image: rf.contentapproval.app:1.0
    mem_limit: 200M
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
    hostname: contentapproval-app
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ${HOME}/.aspnet/https:/https/
    build:
      context: .
      dockerfile: RF.ContentApproval.App/Dockerfile
    restart: always
    depends_on:
      rabbit:
        condition: service_healthy
  contentsearch-app:
    image: rf.contentsearch.app:1.0
    mem_limit: 200M
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
    hostname: contentsearch-app
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ${HOME}/.aspnet/https:/https/
    build:
      context: .
      dockerfile: RF.ContentSearch.App/Dockerfile
    restart: always
    depends_on:
      rabbit:
        condition: service_healthy
  consul:
    image: consul:1.4.3
    mem_limit: 250M
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
    hostname: consul
    ports:
      - "8500:8500"
      - "8600:8600"
    expose:
      - 8500
      - 8600
    restart: always
  rabbit:
    image: rabbitmq:3-management
    mem_limit: 500M
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
    hostname: rabbit
    build: rabbit/.
    ports:
      - "15672:15672"
      - "5672:5672"
    expose:
      - 15672
      - 5672
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:15672"]
      interval: 30s
      timeout: 10s
      retries: 5